doctrine_mongodb:
  default_connection: default
  default_document_manager: default

  connections:
    default:
      server: "%env(MONGODB_URL)%"
    users:
      server: "%env(MONGODB_URL)%"
    employes:
      server: "%env(MONGODB_URL)%"
    clients:
      server: "%env(MONGODB_URL)%"
    fournisseurs:
      server: "%env(MONGODB_URL)%"

  document_managers:
    default:
      connection: default
      database: common
      mappings:
        Common:
          type: annotation
          dir: '%kernel.project_dir%/src/Common'
          prefix: App\Common\Documents
          is_bundle: false

    users:
      connection: users
      database: users
      mappings:
        Users:
          type: annotation
          dir: '%kernel.project_dir%/src/Users'
          prefix: App\Users\Documents
          is_bundle: false

    employes:
      connection: employes
      database: employes
      mappings:
        Users:
          type: annotation
          dir: '%kernel.project_dir%/src/Employes'
          prefix: App\Employes\Documents
          is_bundle: false

    clients:
      connection: clients
      database: clients
      mappings:
        Users:
          type: annotation
          dir: '%kernel.project_dir%/src/Clients'
          prefix: App\Clients\Documents
          is_bundle: false

    fournisseurs:
      connection: fournisseurs
      database: fournisseurs
      mappings:
        Users:
          type: annotation
          dir: '%kernel.project_dir%/src/Fournisseurs'
          prefix: App\Fournisseurs\Documents
          is_bundle: false