version: '3.5'

services:
  kong:
    build: docker/kong
    hostname: api.erp.docker
    volumes:
      - ./docker/kong/kong.yml:/home/kong/kong.yml
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:80
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - 127.55.0.1:8001:8001
      - 127.55.0.1:80:80
      - 127.55.0.1:443:443

  mongodb:
    build: docker/mongodb
    hostname: db.erp.docker
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api-platform
      - MONGO_INITDB_ROOT_PASSWORD=!ChangeMe!
    volumes:
      - database:/var/lib/mongodb/data:rw
    ports:
      - 127.55.0.2:27017:27017

  documentation-api:
    build: docker/php
    working_dir: /home/erp
    volumes:
      - .:/home/erp
      - ./docker/php/vhost_documentation.conf:/etc/apache2/sites-available/000-default.conf
    hostname: documentation.erp.docker
    ports:
      - 127.55.0.10:80:80
      - 127.55.0.10:443:443
    environment:
      MICRO_SERVICE_URLS: 'http://users.erp.docker/;http://common.erp.docker/;http://employes.erp.docker/;http://fournisseurs.erp.docker/'
      API_GATEWAY_URLS: 'http://127.55.0.1/;http://api.erp.docker/'
      MICRO_SERVICE_NAME: Documentation
      API_VERSION: 0.0.0

  users-api:
    build: docker/php
    working_dir: /home/erp
    volumes:
      - .:/home/erp
      - ./docker/php/vhost_users.conf:/etc/apache2/sites-available/000-default.conf
    hostname: users.erp.docker
    ports:
      - 127.55.0.20:80:80
      - 127.55.0.20:443:443
    environment:
      MICRO_SERVICE_NAME: Users
      API_VERSION: 0.0.0

  common-api:
    build: docker/php
    working_dir: /home/erp
    volumes:
      - .:/home/erp
      - ./docker/php/vhost_common.conf:/etc/apache2/sites-available/000-default.conf
    hostname: common.erp.docker
    ports:
      - 127.55.0.30:80:80
      - 127.55.0.30:443:443
    environment:
      MICRO_SERVICE_NAME: Common
      API_VERSION: 0.0.0

  employes-api:
    build: docker/php
    working_dir: /home/erp
    volumes:
      - .:/home/erp
      - ./docker/php/vhost_employes.conf:/etc/apache2/sites-available/000-default.conf
    hostname: employes.erp.docker
    ports:
      - 127.55.0.40:80:80
      - 127.55.0.40:443:443
    environment:
      MICRO_SERVICE_NAME: Employes
      API_VERSION: 0.0.0

  fournisseurs-api:
    build: docker/php
    working_dir: /home/erp
    volumes:
      - .:/home/erp
      - ./docker/php/vhost_fournisseurs.conf:/etc/apache2/sites-available/000-default.conf
    hostname: fournisseurs.erp.docker
    ports:
      - 127.55.0.50:80:80
      - 127.55.0.50:443:443
    environment:
      MICRO_SERVICE_NAME: Fournisseurs
      API_VERSION: 0.0.0

volumes:
  database: ~