services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Fournisseurs\:
        resource: '../../src/Fournisseurs'
        exclude: '../../src/Fournisseurs/{Entity,DependencyInjection,Tests,Kernel.php}/'

    App\Fournisseurs\Decorator\FournisseurDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@App\Fournisseurs\Decorator\FournisseurDecorator.inner']
        autoconfigure: false

    App\Fournisseurs\Decorator\ArticleDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@App\Fournisseurs\Decorator\ArticleDecorator.inner']
        autoconfigure: false

    App\Fournisseurs\Decorator\VersionDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@App\Fournisseurs\Decorator\VersionDecorator.inner']
        autoconfigure: false