services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Users\DataPersister\UtilisateurDataPersister:
        arguments:
            $documentManager: '@doctrine_mongodb.odm.users_document_manager'

    App\Users\Decorator\JwtDecorator:
        arguments:
         - $decorates: '@api_platform.openapi.factory'
        autoconfigure: false