services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Users\:
        resource: '../../src/Users'
        exclude: '../../src/Users/{Entity,DependencyInjection,Tests,Kernel.php}/'

    App\Users\Controller\:
        resource: '../../src/Users/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Users\Decorator\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@App\Users\Decorator\JwtDecorator.inner']
        autoconfigure: false