api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Common/Documents'
            - '%kernel.project_dir%/src/Users/Documents'
            - '%kernel.project_dir%/src/Employes/Documents'