doctrine_mongodb:
  default_connection: default
  default_document_manager: default

  connections:
    default:
      server: "%env(MONGODB_URL)%"

  document_managers:
    default:
      connection: default
      database: employes
      mappings:
        Employes:
          type: annotation
          dir: '%kernel.project_dir%/src/Employes'
          prefix: App\Employes\Documents
          is_bundle: false
