doctrine_mongodb:
  default_connection: default
  default_document_manager: default

  connections:
    default:
      server: "%env(MONGODB_URL)%"

  document_managers:
    default:
      connection: default
      database: common
      mappings:
        Common:
          type: annotation
          dir: '%kernel.project_dir%/src/Common'
          prefix: App\Common\Documents
          is_bundle: false
