doctrine_mongodb:
  default_connection: default
  default_document_manager: default

  connections:
    default:
      server: "%env(MONGODB_URL)%"

  document_managers:
    default:
      connection: default
      database: users
      mappings:
        Users:
          type: annotation
          dir: '%kernel.project_dir%/src/Users'
          prefix: App\Users\Documents
          is_bundle: false
        GesdinetJWTRefreshTokenBundle: ~
