services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Comptabilite\:
        resource: '../../src/Comptabilite'
        exclude: '../../src/Comptabilite/{Entity,DependencyInjection,Tests,Kernel.php}/'