services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Common\:
        resource: '../../src/Common'
        exclude: '../../src/Common/{Entity,DependencyInjection,Tests,Kernel.php}/'