services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Employes\:
        resource: '../../src/Employes'
        exclude: '../../src/Employes/{Entity,DependencyInjection,Tests,Kernel.php}/'