_format_version: "2.1"
_transform: true

services:
  - name: documentation
    url: http://documentation.erp.docker
    routes:
      - name: documentation-api
        strip_path: false
        paths:
          - /api/docs
          - /bundles

  - name: common
    url: http://common.erp.docker
    routes:
      - name: common
        strip_path: false
        paths:
          - /api/adresses
          - /api/contacts
          - /api/domaines
          - /api/devises
          - /api/pays

  - name: users
    url: http://users.erp.docker
    routes:
      - name: users
        strip_path: false
        paths:
          - /api/utilisateurs
          - /api/login_check
          - /api/refresh_token

  - name: employes
    url: http://employes.erp.docker
    routes:
      - name: employes
        strip_path: false
        paths:
          - /api/employes

  - name: fournisseurs
    url: http://fournisseurs.erp.docker
    routes:
      - name: fournisseurs
        strip_path: false
        paths:
          - /api/reference_fournisseurs
          - /api/type_sous_ensembles
          - /api/parametre_fichiers
          - /api/type_parametres
          - /api/sous_ensembles
          - /api/fournisseurs
          - /api/parametres
          - /api/versions
          - /api/articles
          - /api/tarifs