_format_version: "2.1"
_transform: true

services:
  - name: global
    url: http://global.erp.docker
    routes:
      - name: global
        strip_path: false
        paths:
          - /docs

  - name: common
    url: http://common.erp.docker
    routes:
      - name: common
        strip_path: false
        paths:
          - /devises

  - name: users
    url: http://users.erp.docker
    routes:
      - name: users
        strip_path: false
        paths:
          - /utilisateurs

  - name: employes
    url: http://employes.erp.docker
    routes:
      - name: employes
        strip_path: false
        paths:
          - /employes