_format_version: "2.1"
_transform: true

services:
  - name: documentation
    url: http://documentation.erp.docker
    routes:
      - name: documentation-api
        strip_path: false
        paths:
          - /api/docs
          - /bundles

  - name: common
    url: http://common.erp.docker
    routes:
      - name: common
        strip_path: false
        paths:
          - /api/devises

  - name: users
    url: http://users.erp.docker
    routes:
      - name: users
        strip_path: false
        paths:
          - /api/utilisateurs
          - /api/login_check

  - name: employes
    url: http://employes.erp.docker
    routes:
      - name: employes
        strip_path: false
        paths:
          - /api/employes